# This is a YAML file, which stores a full setpoint message.
# This works when called from the command line with
#   rostopic pub -f setpoint.yaml /sam/ctrl/desired_setpoint depth_keeping/Setpoint
depth: -2.0
duration: 1.0
trigger: true
